-- Temporarily disable RLS for migration
ALTER TABLE user_logins DISABLE ROW LEVEL SECURITY;
ALTER TABLE login_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_chats DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_tokens DISABLE ROW LEVEL SECURITY; 